services:
  postgres:
    image: postgres:16
    container_name: operation-conflict-db
    environment:
      POSTGRES_DB: operationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: