spring.application.name=operation-conflict-service
spring.datasource.url=jdbc:postgresql://localhost:5432/operationdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true